spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:onsae}
    username: ${DB_USERNAME:onsae}
    password: ${DB_PASSWORD:onsae}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          preferred_instant_jdbc_type: TIMESTAMP
        globally_quoted_identifiers: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=15m

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.onsae: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  file-upload:
    path: ./uploads-local
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8081
  swagger:
    server-url: http://localhost:8080
